library(recommenderlab)
library(ggplot2)
library(data.table)
library(reshape2)
movie_data <- read.csv("IMDB-Dataset/movies.csv", stringsAsFactors=FALSE)
print(str(movie_data))
rating_data <- read.csv("IMDB-Dataset/ratings.csv")
print(str(rating_data))
print(summary(movie_data))
print(head(movie_data))
print(summary(rating_data))
print(head(rating_data))
